In [9]:
import numpy as np

In [32]:
N_STATES = 5
new_max = np.array([3,1,0,-1,-3], dtype=np.float32)
new_min = np.array([3,1,0,-1,-3], dtype=np.float32)

old_max = -1 *np.array([2,2,2,2,2], dtype=np.float32)
old_min = -1 *np.array([2,2,2,2,2], dtype=np.float32)

newboundary_max = old_max
newboundary_min = old_min

for i in range(N_STATES):
    newboundary_max[i] = new_max[i] if new_max[i] > old_max[i] else (old_max[i]+new_max[i])/2
    newboundary_min[i] = new_min[i] if new_min[i] < old_min[i] else (old_min[i]+new_min[i])/2

newboundary = np.concatenate((newboundary_max,newboundary_min))

In [33]:
newboundary

array([ 3. ,  1. ,  0. , -1. , -2.5,  0.5, -0.5, -1. , -1.5, -3. ],
      dtype=float32)

In [10]:
oldboundary =  np.array([2,  2,  2,   2])
newboundary =  np.array([3 , 1, -1 , -3])

In [16]:
np.mean((2,3))

2.5

In [11]:
def clamp2abs(old, new):
    return new if new > old else (old+new)/2

In [12]:
for i in range(oldboundary.shape[0]):
    print(i, oldboundary[i], newboundary[i], clamp2abs(oldboundary[i],newboundary[i]))

0 2 3 3
1 2 1 1.5
2 2 -1 0.5
3 2 -3 -0.5


In [13]:
vec_clamp = np.vectorize(clamp2abs)

In [14]:
vec_clamp(oldboundary,newboundary)

array([3, 1, 0, 0])

In [36]:
temp

array([3. , 1.5, 1. , 1. ])

In [3]:
np.sort([741 ,9086 ,4507, 7551, 5987, 862, 5955, 5095, 3119, 3664, 6654, 7551, 6118, 7628, 3615, 9948, 7957, 6192, 1259, 2712, 9740, 6040, 1896, 9684, 5584, 3531, 371, 5731, 7100, 1145, 9382, 4068, 3713, 2758, 5632])

array([ 371,  741,  862, 1145, 1259, 1896, 2712, 2758, 3119, 3531, 3615,
       3664, 3713, 4068, 4507, 5095, 5584, 5632, 5731, 5955, 5987, 6040,
       6118, 6192, 6654, 7100, 7551, 7551, 7628, 7957, 9086, 9382, 9684,
       9740, 9948])

In [11]:
x = np.array([5,6,7,8,9])

In [14]:
x[x>=7].shape[0]

3

In [9]:
a = np.array([2, 2, 2, 2, 2])
b = np.array([4, 4, 4 ,4, 4])

mean = a+b/2

6.0


In [7]:
2.6 - 6/40

2.45

In [2]:
NO_OF_NODES = 10

In [12]:
for iteration in range(10):
    print("**")
    for node_id in range(NO_OF_NODES):
        print(np.clip(    ((node_id%5 + 1)*0.1 + (iteration+1)*0.15)   ,0.3,0.9))

**
0.3
0.35
0.45000000000000007
0.55
0.65
0.3
0.35
0.45000000000000007
0.55
0.65
**
0.4
0.5
0.6000000000000001
0.7
0.8
0.4
0.5
0.6000000000000001
0.7
0.8
**
0.5499999999999999
0.6499999999999999
0.75
0.85
0.9
0.5499999999999999
0.6499999999999999
0.75
0.85
0.9
**
0.7
0.8
0.9
0.9
0.9
0.7
0.8
0.9
0.9
0.9
**
0.85
0.9
0.9
0.9
0.9
0.85
0.9
0.9
0.9
0.9
**
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
**
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
**
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
**
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
**
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
0.9
