In [1]:
import numpy as np

In [27]:
init = np.random.rand(5,4,2)

In [28]:
init.shape

(5, 4, 2)

In [39]:
init

array([[[0.32482602, 0.53381962],
        [0.40485876, 0.92901238],
        [0.44988025, 0.1775792 ],
        [0.64455572, 0.48329906]],

       [[0.76923953, 0.64589161],
        [0.90038746, 0.31224534],
        [0.66032428, 0.09383467],
        [0.85990032, 0.45292531]],

       [[0.422897  , 0.50795962],
        [0.92854565, 0.36166346],
        [0.97338973, 0.45487847],
        [0.92269458, 0.62145575]],

       [[0.97750929, 0.09320586],
        [0.02581013, 0.70740217],
        [0.73526094, 0.53141408],
        [0.6550712 , 0.49882258]],

       [[0.86110453, 0.64271794],
        [0.91662188, 0.21197176],
        [0.8783339 , 0.37830751],
        [0.82892257, 0.35519572]]])

In [30]:
final = np.zeros((5,4,3,2))

In [31]:
final.shape

(5, 4, 3, 2)

In [43]:
# final[:,:,0,:] = init
final = np.repeat(init[:,:,np.newaxis,:],3,axis=2)

In [44]:
final.shape

(5, 4, 3, 2)

In [45]:
final

array([[[[0.32482602, 0.53381962],
         [0.32482602, 0.53381962],
         [0.32482602, 0.53381962]],

        [[0.40485876, 0.92901238],
         [0.40485876, 0.92901238],
         [0.40485876, 0.92901238]],

        [[0.44988025, 0.1775792 ],
         [0.44988025, 0.1775792 ],
         [0.44988025, 0.1775792 ]],

        [[0.64455572, 0.48329906],
         [0.64455572, 0.48329906],
         [0.64455572, 0.48329906]]],


       [[[0.76923953, 0.64589161],
         [0.76923953, 0.64589161],
         [0.76923953, 0.64589161]],

        [[0.90038746, 0.31224534],
         [0.90038746, 0.31224534],
         [0.90038746, 0.31224534]],

        [[0.66032428, 0.09383467],
         [0.66032428, 0.09383467],
         [0.66032428, 0.09383467]],

        [[0.85990032, 0.45292531],
         [0.85990032, 0.45292531],
         [0.85990032, 0.45292531]]],


       [[[0.422897  , 0.50795962],
         [0.422897  , 0.50795962],
         [0.422897  , 0.50795962]],

        [[0.92854565, 0.36166346]

In [48]:
a = np.array([10])

In [51]:
a.clip(0,5,out=a)

array([5])

In [52]:
a

array([5])